/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ToolCapability {
  namespace: string
  tool: string
  action: string
}
export interface Owner {
  name: string
  email: string
  team: string
}
export interface ServiceAccountMapping {
  provider: string
  subject: string
}
export interface AgentIdentity {
  identityVersion: string
  agentUuid: string
  agentId: string
  organizationId: string
  environment: string
  owner: Owner
  serviceAccountMappings: Array<ServiceAccountMapping>
  allowedToolCapabilities: Array<ToolCapability>
  allowedNetworkDestinations: Array<string>
  allowedResourceScopes: Array<string>
  deniedToolCapabilities: Array<ToolCapability>
}
export interface PolicyRule {
  id: string
  description: string
  ruleMode?: string
  interrupt: string
  severity: string
  detector: string
  reason: string
  thresholdUsd?: number
  forbiddenTools: Array<ForbiddenTool>
  forbiddenResourcePatterns: Array<string>
  allowedDestinations: Array<string>
}
export interface ForbiddenTool {
  namespace: string
  tool: string
}
export interface PolicySpec {
  policyId: string
  policyVersion: string
  globalMode: string
  rules: Array<PolicyRule>
}
export interface AgentToolCall {
  requestId: string
  agentId: string
  prompt: string
  modelProvider: string
  modelName: string
  modelConfigJson: string
  parentContextJson?: string
  toolNamespace: string
  toolName: string
  action: string
  argumentsJson: string
  resourcesTargeted: Array<string>
  resourcesModified: Array<string>
  networkDestination: string
  receivedTimestamp: string
}
export interface EvaluationLedgerEntry {
  policyId: string
  policyVersion: string
  ruleId: string
  ruleMode: string
  result: string
  reason: string
  severity: string
}
export interface StandardizedAgentError {
  code: string
  message: string
  ruleId: string
}
export interface IngressEnvelope {
  promptHash: string
  modelProvider: string
  modelName: string
  modelConfigHash: string
  parentContextHash: string
}
export interface ActionPayload {
  toolName: string
  toolNamespace: string
  argumentsHash: string
  redactedArgumentsPreviewJson: string
  resourcesTargeted: Array<string>
  resourcesModified: Array<string>
}
export interface ChainOfCustody {
  receivedTimestamp: string
  evaluatedTimestamp: string
  emittedTimestamp: string
  processingNodeId: string
  previousRecordHash?: string
  recordHash: string
  signatureStub: string
}
export interface EvidenceRecord {
  recordId: string
  organizationId: string
  environment: string
  agentId: string
  agentIdentityVersion: string
  humanOwnerOperator: Owner
  actionAllowed: boolean
  standardizedError?: StandardizedAgentError
  ingressEnvelope: IngressEnvelope
  actionPayload: ActionPayload
  evaluationLedger: Array<EvaluationLedgerEntry>
  chainOfCustody: ChainOfCustody
}
export interface AgentResponse {
  ok: boolean
  requestId: string
  error?: StandardizedAgentError
}
export interface SimulationResult {
  mode: string
  actionAllowed: boolean
  agentResponse: AgentResponse
  evidenceRecord: EvidenceRecord
}
/** Usage Intelligence types */
export interface UsageIntelligence {
  llmUsageDetected: boolean
  llmSurface: string
  intentClassification: string
  domainAlignment: string
  riskLevel: string
  riskSignals: Array<string>
  operatorNarrative: string
  recommendedWorkflow: string
}
/** Canonical JSON functions - use String for JSON input/output */
export declare function canonicalJsonSort(value: string): string
export declare function canonicalJsonSerialize(value: string): string
/** Hash functions */
export declare function hashSha256Str(input: string): string
export declare function hashSha256Value(value: string): string
export declare function hashSha256Any(value: string): string
export declare function hashEvidenceRecordNapi(record: string): string
export declare function hashSignRecordStub(recordHash: string): string
/** Policy evaluation functions */
export declare function policyVerifyIdentity(identity: AgentIdentity, call: AgentToolCall): Array<EvaluationLedgerEntry>
export declare function policyEvaluate(policy: PolicySpec, call: AgentToolCall): Array<EvaluationLedgerEntry>
/** Redaction function */
export declare function redactArguments(args: string): string
/** Usage intelligence */
export declare function usageIntelAnalyze(query: string): UsageIntelligence
/** Main trace simulation entry point */
export declare function traceSimulate(identity: AgentIdentity, policy: PolicySpec, call: AgentToolCall, previousRecordHash: string | undefined | null, evaluatedTimestamp: string, emittedTimestamp: string): SimulationResult
export declare function init(): void
