"""Contract tests for auto_generated scripts"""
import asyncio
import json
from pathlib import Path
import pytest
import sys

# Add scripts to path
sys.path.insert(0, str(Path(__file__).parent.parent / "scripts" / "auto_generated"))

# Import the modules
import increase_telemetry
import collect_new_data
import detect_latency_degradation


class TestAutoGeneratedScripts:
    """Contract tests for auto-generated telemetry scripts"""

    def test_increase_telemetry_imports(self):
        """increase_telemetry should import without error."""
        assert increase_telemetry is not None
        assert hasattr(increase_telemetry, "main")
        assert hasattr(increase_telemetry, "BOOST_MULTIPLIER")
        assert hasattr(increase_telemetry, "DURATION_MINUTES")
        assert hasattr(increase_telemetry, "generate_event")

    def test_collect_new_data_imports(self):
        """collect_new_data should import without error."""
        assert collect_new_data is not None
        assert hasattr(collect_new_data, "main")

    def test_detect_latency_degradation_imports(self):
        """detect_latency_degradation should import without error."""
        assert detect_latency_degradation is not None
        assert hasattr(detect_latency_degradation, "main")

    def test_increase_telemetry_constants(self):
        """increase_telemetry should have correct constants."""
        assert increase_telemetry.BOOST_MULTIPLIER == 10
        assert increase_telemetry.DURATION_MINUTES == 60
        assert "8084" in increase_telemetry.MOCK_API_URL

    def test_generate_event_returns_dict(self):
        """generate_event should return a dict with expected structure."""
        event = increase_telemetry.generate_event()
        
        assert isinstance(event, dict)
        required_fields = [
            "timestamp", "request_id", "user_id", "session_id",
            "model", "endpoint", "prompt_tokens", "completion_tokens",
            "latency_ms", "error", "trace_metadata"
        ]
        for field in required_fields:
            assert field in event
        
        assert event["endpoint"] == "/v1/chat/completions"
        assert isinstance(event["prompt_tokens"], int)
        assert isinstance(event["completion_tokens"], int)
        assert isinstance(event["latency_ms"], int)
        assert event["trace_metadata"]["intent"] in [
            "potentially_malicious_or_unsafe",
            "business_sensitive_workflow"
        ]
        assert event["trace_metadata"]["risk_level"] in ["high", "low"]

    def test_sample_queries_defined(self):
        """SAMPLE_QUERIES should be defined with expected attacks."""
        queries = increase_telemetry.SAMPLE_QUERIES
        
        assert isinstance(queries, list)
        assert len(queries) >= 8
        
        # Check for specific attack queries
        attack_queries = [q for q in queries if "hack" in q or "injection" in q]
        assert len(attack_queries) >= 2
        
        benign_queries = [q for q in queries if "hack" not in q and "injection" not in q]
        assert len(benign_queries) >= 4

    def test_models_defined(self):
        """MODELS should be defined."""
        models = increase_telemetry.MODELS
        assert isinstance(models, list)
        assert len(models) >= 4
        assert "gpt-4o" in models
        assert "claude-3.5-sonnet" in models

    @pytest.mark.asyncio
    async def test_main_runs_without_error(self):
        """main() should run without error (with mock)."""
        # Temporarily reduce duration to minimum
        original_duration = increase_telemetry.DURATION_MINUTES
        increase_telemetry.DURATION_MINUTES = 0  # Will exit immediately
        
        try:
            await increase_telemetry.main()
        except Exception as e:
            pytest.fail(f"main() raised {e}")
        finally:
            increase_telemetry.DURATION_MINUTES = original_duration


class TestAutoGeneratedSyntax:
    """Syntax validation for auto-generated scripts."""

    def test_all_scripts_compile(self):
        """All auto-generated scripts should compile."""
        import py_compile
        
        scripts_dir = Path(__file__).parent.parent / "scripts" / "auto_generated"
        for script_path in scripts_dir.glob("*.py"):
            if script_path.name.startswith("__"):
                continue
            py_compile.compile(str(script_path), doraise=True)


if __name__ == "__main__":
    pytest.main([__file__, "-v"])